flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: aad9288f97ed8b662c16764cc2ebc404fead4a11
  extra-dep: true
extra-deps:
- texmath-0.9.4.2
- hslua-0.8.0
- skylighting-0.4.1
- cmark-gfm-0.1.1
- QuickCheck-2.10.0.1
- tasty-quickcheck-0.9.1
- haddock-library-1.4.3
- pandoc-types-1.17.2
# needed for now:
- hs-bibutils-5.5
- rfc5051-0.1.0.3
resolver: lts-9.1
