flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: 49830555fa4a384692ab4ec4e64fdb6c4e7bc78b
  extra-dep: true
extra-deps:
- xml-conduit-1.5.0
- skylighting-0.3.3
resolver: lts-8.16
