flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: 'https://github.com/jgm/pandoc-types'
    commit: c64eb383dce64396290aa815351ddb6e43cb6b0f
  extra-dep: true
- location:
    git: 'https://github.com/jgm/texmath'
    commit: a716e9b5d8c1634847db2c1119e60836634569bf
  extra-dep: true
- location:
    git: 'https://github.com/jgm/pandoc'
    commit: HEAD
  extra-dep: true
extra-deps: []
resolver: lts-3.13
