flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: e07e83f83177095651b201f489855baafeec49c2
  extra-dep: true
extra-deps:
# - pandoc-1.19.2
- skylighting-0.1.1.4
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- texmath-0.9
# - skylighting-0.1.1.2
resolver: lts-7.14
