flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- pandoc-2.2.3.2
- haddock-library-1.6.0
- HsYAML-0.1.1.1
- network-2.7.0.2
- rfc5051-0.1.0.3
- hs-bibutils-6.5.0.0
ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-12.0
