flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: 8f90b83feec3ac9474b3f059a0dff43bd6e88f8b
  extra-dep: true
extra-deps:
- xml-conduit-1.5.0
- skylighting-0.3.1
- texmath-0.9.3
resolver: lts-8.4
