flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc-types.git
    commit: 6580565f7271eb2d15a4d71c3415316850f47b29
- location:
    git: https://github.com/jgm/pandoc.git
    commit: 6156cdda13ee5f9edbb11a672f6eb78631c3ffc5
extra-deps:
- texmath-0.8.6.6
- doctemplates-0.1.0.2
resolver: lts-7.2
