flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: b68135d34dfc0e53ca0aa5db4be3f4a2359001f4
  extra-dep: true
extra-deps:
- xml-conduit-1.5.0
- skylighting-0.3.3
resolver: lts-8.11
