flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- texmath-0.8.6.6
resolver: lts-7.2
