flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: fb8a2540bdb91eee0ecf620b4e9d7acf3d78042f
extra-deps:
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- texmath-0.9
resolver: lts-7.9
