flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: cfdbe85e7178e2a82f141192736dc2e0d6daed8a
  extra-dep: true
extra-deps:
- xml-conduit-1.5.0
resolver: lts-8.0
