flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: bd71569483e8b471bcd94203e6f7be6b47b65280
extra-deps:
- texmath-0.8.6.6
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
resolver: lts-7.4
