flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- 'aeson-pretty-0.8.1'
resolver: lts-6.5
