flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- rfc5051-0.1.0.3
- pandoc-2.1
- hslua-0.9.5
- skylighting-0.5.1
resolver: lts-10.2
