flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- 'http-client-0.5.0'
- 'http-client-tls-0.3.0'
resolver: lts-7.0
