flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
# - location:
#     git: https://github.com/jgm/pandoc.git
#     commit: 411434bf130a3116290c7ca54358678e03d0d92b
#   extra-dep: true
extra-deps:
- pandoc-1.19.1
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- texmath-0.9
# - skylighting-0.1.1.2
resolver: lts-7.14
