flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: 55d679e382954dd458acd6233609851748522d99
  extra-dep: true
extra-deps:
- xml-conduit-1.5.0
- skylighting-0.3.3
resolver: lts-8.16
