flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: 35922ffa324eaba4e853a7c4b5517ddb505723a1
  extra-dep: true
extra-deps:
- xml-conduit-1.5.0
- skylighting-0.3
resolver: lts-8.2
