flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc.git
    commit: 31076adf090b8b87f5bab90c8b91f872f81aa2bd
extra-deps:
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
resolver: lts-7.5
